import { GetLayout } from '@src/pages/_app'
import Head from 'next/head'
import Footer from '../../Footer'
import Header from '../../Header'
import styles from './style.module.css'

const Layout: GetLayout = (page) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.wrapper}>
        <Header />
        <main className={styles.main}>{page}</main>
        <Footer />
      </div>
    </>
  )
}

export default Layout
