'use client'

import MainLayout from '@ui/layout/Main'
import Head from 'next/head'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link href='https://fonts.googleapis.com/css?family=Noto+Sans+JP' rel='stylesheet' />
      </Head>
      <MainLayout>{children}</MainLayout>
    </html>
  )
}
