import type { NextPage } from 'next'
import Head from 'next/head'
// import 'normalize.css'

import Layout from '@src/components/ui/Layout'
import PageList from '@src/components/PageList'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h1>title</h1>
        <PageList />
      </Layout>
    </div>
  )
}

export default Home
